/*
 * CliTool.java
 *
 * Copyright 2017-2018 Dariusz Sikora <dev@isangeles.pl>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 *
 *
 */
package pl.isangeles.senlin.cli.tools;

/**
 * Interface for CLI tools All CLI tools must provide output of commands in form of string array
 * with elements: [0]-result(0 success, 0< error), [1]output text(out generated by command) output
 * signals codes: 0 - success 1 - option error 2 - 3 - 4 - 5 - syntax error 6 -
 *
 * @author Isangeles
 */
public interface CliTool {
  /**
   * Returns tool name
   *
   * @return String with tool name
   */
  public String getName();
  /**
   * Handles specified command
   *
   * @param command Command to handle
   * @return String with result[0](0 success, 0< error) and output[1] of specified command
   */
  public String[] handleCommand(String command);
  /**
   * Checks if this tool is same as tool with specified name
   *
   * @param name String with tool name
   * @return True if tool name equals specified name, false otherwise
   */
  public boolean equals(String name);
}
